name: Daily Reviews WhatsApp

on:
  schedule:
    - cron: "30 1 * * *"  # Runs every day at 7:00 AM IST (1:30 AM UTC)
  workflow_dispatch:       # Lets you trigger manually too

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install google-play-scraper pandas twilio pytz

      - name: Run script
        env:
          TWILIO_SID: ${{ secrets.TWILIO_SID }}
          TWILIO_AUTH: ${{ secrets.TWILIO_AUTH }}
        run: python main.py
